### ISSUE TITLE
[1.17.1] Client crash after death. java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing

### ISSUE THREAD

**Issue by ProsperCraft** [grim3212/AssortedTech#1]
Died and when I was loading in to my base with Assorted tech in it, my client crashed.

https://gist.github.com/ProsperCraft/6fd28a5f1809a2b29b39a9a569b906a6

assortedtech-1.17.1-1.0.2

**Comment by grim3212** [comment]
Thanks, for the report. The latest version `assortedtech-1.17.1-1.0.3` should fix this issue. Closed by 31e41d9
