### ISSUE TITLE
Fan Particles

### ISSUE THREAD

**Issue by Katsunsama** [grim3212/AssortedTech#2]
Im not sure how to reproduce this because it wasnt always like this.

It's "fixable" by disabling fan particles in the config but if you turn them back on it stays this way. 

![image](https://user-images.githubusercontent.com/92512805/148506624-1e8ff361-ea6c-48f4-9d31-2dc9ae4867d0.png)

Minecraft 1.18.1 | Forge 39.0.6 | Assorted Core 3.1.0 | Assorted Tech 2.1.0

**Comment by grim3212** [comment]
The fan particles I am totally unsure what is going on. Sometimes they work, sometimes they don't appear, and sometimes they get all corrupted like this. I think it has to do when registered but I have yet to be able to track this down yet.

**Comment by grim3212** [comment]
I think this has been fixed with the latest version. Closing for now.
