### ISSUE TITLE
Does not run server-side

### ISSUE THREAD

**Issue by ubkh** [grim3212/AssortedTech#3]
The TechParticleTypes class references an AirParticleType object that contains client-side-only code, and is present directly in the constructor for the main class, causing it to crash at runtime when run on a server. I've attached a crash report.

[crash-2022-06-22_12.06.59-fml.txt](https://github.com/grim3212/AssortedTech/files/8957263/crash-2022-06-22_12.06.59-fml.txt)

**Comment by grim3212** [comment]
The latest version `3.1.1` should fix this. Thanks for the report!
