### ISSUE TITLE
Hide spikes uncraftable from JEI 

### ISSUE THREAD

**Issue by TheDeviantCrafter** [grim3212/AssortedTech#4]
My modpack doesn't include peridot. Peridot spikes still appear in JEI, including a broken crafting recipe:

![image](https://user-images.githubusercontent.com/18755309/190289583-25767e27-807f-486f-8f00-fea09ebeb16b.png)

The mod should check if the tag `forge:gems/peridot` contains anything, and if not, hide the spike from JEI.

**Comment by grim3212** [comment]
It should be doing this already. What version is this on?

**Comment by TheDeviantCrafter** [comment]
1.18.2-3.1.1

**Comment by grim3212** [comment]
Hmm, I guess I figured if the recipe was uncraftable JEI would hide it anyway. I see the same thing.

I'll look into fixing this.

**Comment by TheDeviantCrafter** [comment]
If it's not clear I would like the entire item to be hidden from JEI, not just the recipe.

**Comment by grim3212** [comment]
Okay, latest update includes recipe condition fixes as well as a config option to hide uncraftable items.
