### ISSUE TITLE
Make bridge and gravity lift projections transparent

### ISSUE THREAD

**Issue by TheDeviantCrafter** [grim3212/AssortedTech#5]
Making the texture transparent like glass would make it feel much more like an energy projection.

**Comment by grim3212** [comment]
The gravity lift is mostly transparent as for the bridges at least for the ones you can collide with they are meant to at least seem somewhat sturdy.

Feel free to add a resource pack though to change it out. I am horrible with texturing so I think I am going to leave them as is for right now.
